### ISSUE TITLE
não consigo utilizar o Plugin

### ISSUE THREAD

**Issue by vieirajunior** [faunalia/rt_mapserver_exporter#19]
Toda vez que vou utilizar o plugin aprece essa mensagem erro: 

Traceback (most recent call last):
			  File "C:/Users/LABTEC 348/.qgis2/python/plugins\rt_mapserver_exporter\plugin.py", line 65, in run
			    from .mapfileexportdlg import MapfileExportDlg
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/LABTEC 348/.qgis2/python/plugins\rt_mapserver_exporter\mapfileexportdlg.py", line 31, in <module>
			    import MapfileExporter
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/LABTEC 348/.qgis2/python/plugins\rt_mapserver_exporter\MapfileExporter.py", line 9, in <module>
			    from utils import *
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/LABTEC 348/.qgis2/python/plugins\rt_mapserver_exporter\utils.py", line 1, in <module>
			    import mapscript
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			ImportError: No module named mapscript 

![capturar2](https://user-images.githubusercontent.com/38508192/38953410-06e31f90-4325-11e8-9574-08ea96a80f1f.JPG)

![capturar3](https://user-images.githubusercontent.com/38508192/38953459-322bfc80-4325-11e8-9284-0904ced11187.JPG)

como posso resolver isso.

**Comment by pcav** [comment]
No module named mapscript

so you have to install mapscript.
However, please note that we do not recommend using this plugin. Better using QGIS server instead.
