### ISSUE TITLE
 Problemi nell'esecuzione del plugin

### ISSUE THREAD

**Issue by tierix** [faunalia/rt_mapserver_exporter#4]
Devo per forza scrivere in inglese? mi ci taglio un pò..e non sono nemmeno un'informatica. Vabè provo comunque a segnalarvi il problema. Eseguendo il plugin viene fuori questo messaggio:

Errore durante l'esecuzione di codice Python:

Traceback (most recent call last):
 File "C:/Users/Terry/.qgis2/python/plugins\rt_mapserver_exporter\plugin.py, line 65, in run from .mapfileexportdlg import MapfileExportDlg
 File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import mod = _builtin_import(name, globals, locals, fromlist, level)
 File "C:/Users/Terry/.qgis2/python/plugins\rt_mapserver_exporter\mapfileexportdlg.py", line 30, in import mapscript
 File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import mod = _builtin_import(name, globals, locals, fromlist, level)
 ImportError: No module named mapscript

versione di QGis adoperata: 2.8 e precedente
versione di sistema operativo: Windows 8.1

**Comment by pcav** [comment]
Please have a look to the plugin page: http://plugins.qgis.org/plugins/rt_mapserver_exporter/
- this is not the plugin bugtracker
- in the About, it is clearly stated that "It needs python-mapscript istalled in your machine".
  Anyway, you will probably have more joy using QGIS server instead.

**Comment by tierix** [comment]
E invece ho risolto...... :) ;)

**Comment by pcav** [comment]
Yes, that's easy, but still I predict little joy, compared to QGIS Server.

**Comment by tierix** [comment]
Ok, but I had a problem and now it is resolved! Next step: to work with RT_MAPSERVER_EXPORT to discover it.
Bye
